name: AdGuard DNS Filter
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "5 8 * * 1,4" # biweekly
env:
  TELEGRAM_TO: ${{ secrets.TELEGRAM_TO }}
  TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
jobs:
  getFilter:
    permissions: write-all
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    name: Get Filter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Get Sing-Box Latest Tag
        id: latest_tag
        uses: pozetroninc/github-action-get-latest-release@master
        with:
          repository: SagerNet/sing-box
          excludes: "prerelease, draft"
      - name: Set Environment Variables
        run: |
          echo "Adguard_Filter_Name=adguard-dns-filter" >> $GITHUB_ENV
          echo "Filter_Link=https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_15_DnsFilter/filter.txt" >> $GITHUB_ENV
          SINGBOX_TAG="${{ steps.latest_tag.outputs.release }}"
          SINGBOX_VERSION="${SINGBOX_TAG#v}"
          echo "Singbox_Version=${SINGBOX_VERSION}" >> $GITHUB_ENV
          echo "Singbox_Download_Link=https://www.github.com/SagerNet/sing-box/releases/download/${SINGBOX_TAG}/sing-box-${SINGBOX_VERSION}-linux-amd64.tar.gz" >> $GITHUB_ENV
      - name: Download and Convert Filters
        run: |
          echo "::group::Filter Downloading and Conversion"

          # Download filter
          echo "::notice::Downloading filter..."
          if curl -sSL $Filter_Link -o "${Adguard_Filter_Name}"; then
            echo "::notice::Filter downloaded successfully!"
          else
            echo "::error::Filter download failed!" >&2
            exit 1
          fi

          # Download Sing-Box
          echo "::notice::Downloading Sing-Box..."
          if curl -sSL -o ./sing-box.tar.gz $Singbox_Download_Link; then
            echo "::notice::Sing-Box downloaded successfully!"
          else
            echo "::error::Sing-Box download failed!" >&2
            exit 1
          fi

          # Extract Sing-Box
          echo "::notice::Extracting Sing-Box..."
          if tar -xavf ./sing-box.tar.gz ; then
            echo "::notice::Sing-Box extracted successfully!"
          else
            echo "::error::Sing-Box extraction failed!" >&2
            exit 1
          fi

          sb="sing-box-${Singbox_Version}-linux-amd64/sing-box"
          chmod +x $sb

          # Convert the filter
          echo "::notice::Converting filter..."
          if $sb rule-set convert -t adguard "${Adguard_Filter_Name}"; then
            echo "::notice::Filter converted successfully!"
          else
            echo "::error::Filter conversion failed!" >&2
            exit 1
          fi
          echo "::endgroup::"
      - name: Send Filter via Telegram
        run: |
          chmod +x ./script/*.sh
          echo "::notice::Sending filter via Telegram..."
          ./script/tgSendDoc.sh ${Adguard_Filter_Name} "Plain"
          ./script/tgSendDoc.sh "${Adguard_Filter_Name}.srs" "SRS"
          echo "::notice::Filters sent successfully!"
      - name: Push to "subscribe" branch
        run: |
          branch="subscribe"
          mkdir -p $branch
          cd $branch
          GITPUSH=(git push https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} "$branch")
          git init
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git remote add origin "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
          git checkout -b $branch
          _check_branch=$(git ls-remote --heads origin ${branch})
          #
          if [[ -z ${_check_branch} ]]; then
              echo "Branch $branch do not exist" > /dev/null 2>&1
          else
              echo "Branch exist, need sync" > /dev/null 2>&1
              git fetch origin $branch
              git pull origin $branch
          fi
          NOW=$(date +'%F-%H%M')
          echo -e "# Subscribe dlc\n\n" > README.md
          echo $NOW >> README.md
          cp -r ../"${Adguard_Filter_Name}"* ./
          git add .
          git commit -asm "Updated ${Adguard_Filter_Name} on $NOW" && "${GITPUSH[@]}"
